[package]
name = "ganymede-pattern-macro"
version = "0.1.0"
edition = "2024"
description = "Procedural macro support for Ganymede binary patterns"
license-file.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
ganymede-pattern-core.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn = "2.0.118"
