[package]
name = "ganymede-elf"
version = "0.1.0"
edition = "2024"
description = "ELF interpretation over format-neutral process memory"
license-file.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
catalejo.workspace = true
ganymede-process.workspace = true
ganymede-text.workspace = true
num-traits.workspace = true
thiserror.workspace = true

[build-dependencies]
bindgen.workspace = true
