[package]
name = "ganymede-linker-gnu"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
catalejo.workspace = true
ganymede-elf.workspace = true
ganymede-module.workspace = true
ganymede-process.workspace = true
ganymede-text.workspace = true
num-traits.workspace = true
thiserror.workspace = true

[build-dependencies]
bindgen.workspace = true
prettyplease.workspace = true
syn.workspace = true
